import type { Case, Entity, Relationship, NLPItem, PatternAnomaly, TimelineEvent, AuditLog } from '../types';

export const MOCK_CASES: Case[] = [
  {
    id: 'case-2291',
    title: 'Operativa Syndicate - Cross-Border Narcotics & Laundering',
    caseNumber: 'CASE-2026-2291',
    status: 'UNDER_INVESTIGATION',
    threatLevel: 'CRITICAL',
    leadInvestigator: 'Det. Insp. Marcus Vance (Badge #8804)',
    entityCount: 42,
    relationshipCount: 87,
    lastUpdated: '2026-08-25T14:30:00Z',
    description: 'Multi-jurisdictional syndicate operating illicit wire transfers, vehicle smuggling networks, and burner phone communications in Metro Sector 4.',
    targetCell: 'Red Horizon Operations Cell',
    tags: ['Money Laundering', 'Narcotics', 'CDR Clustering', 'High Priority']
  },
  {
    id: 'case-1048',
    title: 'Redline Maritime Smuggling Network',
    caseNumber: 'CASE-2026-1048',
    status: 'OPEN',
    threatLevel: 'HIGH',
    leadInvestigator: 'Sr. Analyst Sarah Chen (Badge #4921)',
    entityCount: 28,
    relationshipCount: 54,
    lastUpdated: '2026-08-24T18:15:00Z',
    description: 'Coastal logistics firm laundering proceeds via vessel chartering accounts and GPS-masked transponders.',
    targetCell: 'Port Operations Alpha',
    tags: ['Maritime', 'Contraband', 'GPS Spoofing']
  },
  {
    id: 'case-4412',
    title: 'Apex Cyber Syndicate - Ransomware Cashout Ring',
    caseNumber: 'CASE-2026-4412',
    status: 'UNDER_INVESTIGATION',
    threatLevel: 'HIGH',
    leadInvestigator: 'Cyber Agent D. Kowalski (Badge #1109)',
    entityCount: 35,
    relationshipCount: 71,
    lastUpdated: '2026-08-25T09:45:00Z',
    description: 'Decentralized crypto mixer cashout network funneling funds through local shell bank accounts.',
    targetCell: 'Apex Crypto Cell',
    tags: ['Cybercrime', 'Crypto Mixer', 'Shell Accounts']
  },
  {
    id: 'case-0982',
    title: 'Ironclad Logistics Procurement Fraud',
    caseNumber: 'CASE-2026-0982',
    status: 'OPEN',
    threatLevel: 'MEDIUM',
    leadInvestigator: 'FinInt Analyst Alex Mercer',
    entityCount: 16,
    relationshipCount: 29,
    lastUpdated: '2026-08-22T11:20:00Z',
    description: 'Fraudulent municipal contract biddings linked to fictitious vendor addresses.',
    targetCell: 'Procurement Cell B',
    tags: ['Corruption', 'Contract Fraud']
  },
  {
    id: 'case-8831',
    title: 'Vanguard Weapons Trafficking Ring',
    caseNumber: 'CASE-2026-8831',
    status: 'CLOSED',
    threatLevel: 'LOW',
    leadInvestigator: 'Capt. R. Davis',
    entityCount: 52,
    relationshipCount: 110,
    lastUpdated: '2026-07-19T16:00:00Z',
    description: 'Archived case on illegal firearm movement along Interstate 95 corridor.',
    targetCell: 'Vanguard Cell',
    tags: ['Arms Trafficking', 'Resolved']
  }
];

export const MOCK_ENTITIES: Entity[] = [
  {
    id: 'ent-1',
    name: 'Viktor "The Architect" Rostov',
    type: 'person',
    riskScore: 96,
    threatLevel: 'CRITICAL',
    confidenceScore: 94,
    sourceTag: 'CRIMINAL_DB',
    centrality: { degree: 18, betweenness: 0.89, pageRank: 0.092 },
    aliases: ['Viktor R.', 'The Architect', 'V-Boss'],
    phone: '+1 (555) 902-8819',
    coordinates: [40.7128, -74.0060],
    locationName: 'New York, NY (Primary Hub)',
    associatedCaseIds: ['case-2291'],
    notesCount: 14,
    aiFlags: ['Key Cell Leader', 'Bridge Node Connecting 3 Sub-Networks', 'Unusual Financial Velocity'],
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    roleDescription: 'Primary Ring Leader & Financial Decision Maker',
    attributes: { 'DOB': '1978-04-12', 'Citizenship': 'Dual US/CY', 'Interpol Red Notice': 'ACTIVE-A-4901' }
  },
  {
    id: 'ent-2',
    name: 'Elena Rostova (Shell Manager)',
    type: 'person',
    riskScore: 84,
    threatLevel: 'HIGH',
    confidenceScore: 91,
    sourceTag: 'FINANCIAL',
    centrality: { degree: 14, betweenness: 0.72, pageRank: 0.075 },
    aliases: ['Elena Vance', 'E. Rostova'],
    phone: '+1 (555) 431-9022',
    coordinates: [40.7306, -73.9352],
    locationName: 'Queens, NY',
    associatedCaseIds: ['case-2291', 'case-4412'],
    notesCount: 8,
    aiFlags: ['High Transfer Frequency', 'Authorized Signatory on 5 Shell Accounts'],
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    roleDescription: 'Chief Financial Operator & Account Controller',
    attributes: { 'Passport': 'US-9918231', 'Tax ID': 'XX-XXX4910' }
  },
  {
    id: 'ent-3',
    name: 'Apex Global Holdings Ltd (Shell Co)',
    type: 'organization',
    riskScore: 90,
    threatLevel: 'CRITICAL',
    confidenceScore: 98,
    sourceTag: 'FIR',
    centrality: { degree: 16, betweenness: 0.81, pageRank: 0.084 },
    associatedCaseIds: ['case-2291', 'case-1048'],
    notesCount: 19,
    aiFlags: ['Fictitious Office Address', 'Circular Wire Recipient'],
    locationName: 'Financial District, NY',
    coordinates: [40.7075, -74.0089],
    attributes: { 'Registration': 'DEL-2023-8819', 'Declared Capital': '$5,000,000' }
  },
  {
    id: 'ent-4',
    name: 'Burner MSISDN +1-555-019-4821',
    type: 'phone',
    riskScore: 78,
    threatLevel: 'MEDIUM',
    confidenceScore: 88,
    sourceTag: 'CDR',
    centrality: { degree: 11, betweenness: 0.54, pageRank: 0.048 },
    phone: '+1 (555) 019-4821',
    associatedCaseIds: ['case-2291'],
    notesCount: 5,
    aiFlags: ['IMEI Swapped 4 Times', 'Pre-Incident Short Call Burst'],
    attributes: { 'Carrier': 'Prepaid MVNO', 'Activation Date': '2026-08-01' }
  },
  {
    id: 'ent-5',
    name: 'Black SUV - Plate NY-771-X99',
    type: 'vehicle',
    riskScore: 82,
    threatLevel: 'HIGH',
    confidenceScore: 95,
    sourceTag: 'SURVEILLANCE',
    centrality: { degree: 9, betweenness: 0.42, pageRank: 0.039 },
    vehiclePlate: 'NY-771-X99',
    coordinates: [40.7580, -73.9855],
    locationName: 'Midtown Manhattan (ALPR Hit)',
    associatedCaseIds: ['case-2291'],
    notesCount: 6,
    aiFlags: ['Multiple ALPR Hits Near Warehouses', 'Linked to Viktor Rostov'],
    attributes: { 'Make/Model': '2024 Cadillac Escalade Black', 'VIN': '1GYS4HKJ9RR192831' }
  },
  {
    id: 'ent-6',
    name: 'Warehouse Pier 42 Depot',
    type: 'location',
    riskScore: 88,
    threatLevel: 'HIGH',
    confidenceScore: 92,
    sourceTag: 'SURVEILLANCE',
    centrality: { degree: 12, betweenness: 0.63, pageRank: 0.059 },
    coordinates: [40.7101, -73.9785],
    locationName: 'Pier 42 Marine Terminal, NY',
    associatedCaseIds: ['case-2291', 'case-1048'],
    notesCount: 11,
    aiFlags: ['Co-Location Hotspot', 'Night Surveillance Activity'],
    attributes: { 'Zoning': 'Industrial/Port', 'Lease Holder': 'Apex Global Holdings' }
  },
  {
    id: 'ent-7',
    name: 'Chase Account #****-9921 (Apex Primary)',
    type: 'account',
    riskScore: 92,
    threatLevel: 'CRITICAL',
    confidenceScore: 99,
    sourceTag: 'FINANCIAL',
    centrality: { degree: 15, betweenness: 0.79, pageRank: 0.078 },
    accountNumber: 'CHASE-778-9921-X',
    associatedCaseIds: ['case-2291'],
    notesCount: 9,
    aiFlags: ['Rapid In-Out Wire Funneling', '$1.4M Outflow in 24 Hours'],
    attributes: { 'Bank': 'JPMorgan Chase', 'Branch': 'Wall Street NYC' }
  },
  {
    id: 'ent-8',
    name: 'Dmitri "The Hammer" Volkov',
    type: 'person',
    riskScore: 89,
    threatLevel: 'HIGH',
    confidenceScore: 87,
    sourceTag: 'INTEL_REPORT',
    centrality: { degree: 10, betweenness: 0.49, pageRank: 0.045 },
    aliases: ['Hammer Dmitri', 'D-Volk'],
    phone: '+1 (555) 772-1002',
    coordinates: [40.7484, -73.9857],
    locationName: 'Empire State Corridor',
    associatedCaseIds: ['case-2291'],
    notesCount: 7,
    aiFlags: ['Enforcer Role', 'Direct Link to Rostov'],
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    roleDescription: 'Field Operations & Enforcer',
    attributes: { 'Criminal History': 'Prior Convictions (Extortion, Assault)' }
  },
  {
    id: 'ent-9',
    name: 'Offshore Trust - Grand Cayman #881',
    type: 'account',
    riskScore: 85,
    threatLevel: 'HIGH',
    confidenceScore: 84,
    sourceTag: 'FINANCIAL',
    centrality: { degree: 8, betweenness: 0.38, pageRank: 0.038 },
    accountNumber: 'CAYMAN-INT-88102',
    associatedCaseIds: ['case-2291', 'case-4412'],
    notesCount: 4,
    aiFlags: ['Ultimate Beneficiary Obfuscated'],
    attributes: { 'Jurisdiction': 'Cayman Islands' }
  },
  {
    id: 'ent-10',
    name: 'Illicit Transfer Event - $450,000',
    type: 'event',
    riskScore: 94,
    threatLevel: 'CRITICAL',
    confidenceScore: 96,
    sourceTag: 'FINANCIAL',
    centrality: { degree: 7, betweenness: 0.31, pageRank: 0.032 },
    coordinates: [40.7060, -74.0088],
    locationName: 'Financial District Wire Portal',
    associatedCaseIds: ['case-2291'],
    notesCount: 3,
    aiFlags: ['Structured Transaction Below SAR Threshold'],
    attributes: { 'Amount': '$450,000.00', 'Timestamp': '2026-08-24 23:14:02 UTC' }
  },
  {
    id: 'ent-11',
    name: 'Marco "Zero" Rossi',
    type: 'person',
    riskScore: 71,
    threatLevel: 'MEDIUM',
    confidenceScore: 85,
    sourceTag: 'SOCMINT',
    centrality: { degree: 7, betweenness: 0.28, pageRank: 0.029 },
    aliases: ['Agent Zero', 'M. Rossi'],
    phone: '+1 (555) 321-9988',
    coordinates: [40.7282, -73.9942],
    locationName: 'SoHo, NYC',
    associatedCaseIds: ['case-2291'],
    notesCount: 4,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    roleDescription: 'Logistics Liaison & Driver',
    attributes: { 'Social Handle': '@m_rossi_nyc' }
  },
  {
    id: 'ent-12',
    name: 'Port Safe Logistics Inc.',
    type: 'organization',
    riskScore: 68,
    threatLevel: 'MEDIUM',
    confidenceScore: 90,
    sourceTag: 'FIR',
    centrality: { degree: 6, betweenness: 0.22, pageRank: 0.024 },
    associatedCaseIds: ['case-1048'],
    notesCount: 3,
    locationName: 'Brooklyn Navy Yard',
    coordinates: [40.7003, -73.9712],
    attributes: { 'Status': 'Active Freight Forwarder' }
  }
];

export const MOCK_RELATIONSHIPS: Relationship[] = [
  {
    id: 'rel-1',
    source: 'ent-1',
    target: 'ent-2',
    type: 'ASSOCIATION',
    label: 'Direct Command / Co-Conspirator',
    confidence: 96,
    verified: true,
    thickness: 5,
    frequency: 'Daily Contact',
    lastTimestamp: '2026-08-25T12:00:00Z',
    sourceDoc: 'FIR-2026-8891 (Wiretap Order #401)',
    aiFlagged: false
  },
  {
    id: 'rel-2',
    source: 'ent-1',
    target: 'ent-3',
    type: 'OWNERSHIP',
    label: 'Beneficial Owner (100% Control)',
    confidence: 98,
    verified: true,
    thickness: 4,
    sourceDoc: 'FinCEN SAR #992019',
    aiFlagged: false
  },
  {
    id: 'rel-3',
    source: 'ent-2',
    target: 'ent-7',
    type: 'FINANCIAL',
    label: 'Signatory & Wire Initiator',
    confidence: 99,
    verified: true,
    thickness: 5,
    amount: '$2,450,000 Cumulative',
    sourceDoc: 'Chase Bank Records Subpoena #882',
    aiFlagged: true,
    aiReason: 'High frequency wire transfers initiated within 10-min window'
  },
  {
    id: 'rel-4',
    source: 'ent-7',
    target: 'ent-9',
    type: 'FINANCIAL',
    label: 'Wire Outflow ($450,000)',
    confidence: 92,
    verified: true,
    thickness: 4,
    amount: '$450,000.00',
    lastTimestamp: '2026-08-24T23:14:02Z',
    sourceDoc: 'SWIFT Message MT103 Ref #SW-99120',
    aiFlagged: true,
    aiReason: 'Circular transfer detected to offshore entity'
  },
  {
    id: 'rel-5',
    source: 'ent-1',
    target: 'ent-4',
    type: 'COMMUNICATION',
    label: 'Encrypted Voice Calls (CDR)',
    confidence: 88,
    verified: true,
    thickness: 3,
    frequency: '42 Call Logs (Avg 45s duration)',
    lastTimestamp: '2026-08-25T01:30:00Z',
    sourceDoc: 'Telco Intercept CDR Batch #44',
    aiFlagged: true,
    aiReason: 'Pre-incident short-duration call burst before Pier 42 meetup'
  },
  {
    id: 'rel-6',
    source: 'ent-4',
    target: 'ent-8',
    type: 'COMMUNICATION',
    label: 'SMS & Call Traffic',
    confidence: 85,
    verified: true,
    thickness: 3,
    frequency: '18 Encrypted SMS',
    sourceDoc: 'Telco Intercept CDR Batch #44',
    aiFlagged: false
  },
  {
    id: 'rel-7',
    source: 'ent-8',
    target: 'ent-5',
    type: 'OWNERSHIP',
    label: 'Registered Driver / User',
    confidence: 94,
    verified: true,
    thickness: 3,
    sourceDoc: 'DMV Registration Lookup NY-771-X99',
    aiFlagged: false
  },
  {
    id: 'rel-8',
    source: 'ent-5',
    target: 'ent-6',
    type: 'CO_LOCATION',
    label: 'ALPR Surveillance Camera Hit',
    confidence: 91,
    verified: true,
    thickness: 4,
    frequency: '7 Camera Hits (02:00 - 04:30 AM)',
    lastTimestamp: '2026-08-24T03:15:00Z',
    sourceDoc: 'NYPD ALPR Network Log #9910',
    aiFlagged: true,
    aiReason: 'Unusual late night warehouse docking activity'
  },
  {
    id: 'rel-9',
    source: 'ent-1',
    target: 'ent-8',
    type: 'ASSOCIATION',
    label: 'Enforcer Command Link',
    confidence: 93,
    verified: true,
    thickness: 4,
    sourceDoc: 'Surveillance Report SURV-2026-09',
    aiFlagged: false
  },
  {
    id: 'rel-10',
    source: 'ent-11',
    target: 'ent-5',
    type: 'ASSOCIATION',
    label: 'Spotted Driving Vehicle',
    confidence: 76,
    verified: false,
    thickness: 2,
    sourceDoc: 'SOCMINT Photo Tag matching',
    aiFlagged: true,
    aiReason: 'Inferred link via Facial Recognition match on Instagram post'
  },
  {
    id: 'rel-11',
    source: 'ent-3',
    target: 'ent-6',
    type: 'OWNERSHIP',
    label: 'Property Lease Holder',
    confidence: 97,
    verified: true,
    thickness: 3,
    sourceDoc: 'County Deed Registry Doc #88491',
    aiFlagged: false
  },
  {
    id: 'rel-12',
    source: 'ent-7',
    target: 'ent-10',
    type: 'FINANCIAL',
    label: 'Generated Transaction Event',
    confidence: 99,
    verified: true,
    thickness: 5,
    amount: '$450,000.00',
    aiFlagged: true,
    aiReason: 'Transaction flagged as SAR trigger'
  }
];

export const MOCK_NLP_ITEMS: NLPItem[] = [
  {
    id: 'nlp-1',
    textSnippet: 'According to Confidential Informant CI-409, Viktor "The Architect" Rostov instructed Elena Rostova to wire funds to Chase Account #****-9921 before midnight.',
    extractedName: 'Viktor "The Architect" Rostov',
    extractedType: 'person',
    confidenceScore: 96,
    sourceDocument: 'FIR-2026-8891 (Page 4, Para 2)',
    status: 'PENDING'
  },
  {
    id: 'nlp-2',
    textSnippet: 'Vehicle NY-771-X99 was observed leaving Pier 42 Terminal at 03:15 AM heading toward Manhattan financial district.',
    extractedName: 'NY-771-X99',
    extractedType: 'vehicle',
    confidenceScore: 92,
    sourceDocument: 'Surveillance Log SURV-2026-09',
    status: 'PENDING'
  },
  {
    id: 'nlp-3',
    textSnippet: 'Intercepted SMS from +1-555-019-4821 mentioned: "The shipment at Grand Cayman #881 is confirmed for Tuesday".',
    extractedName: 'Grand Cayman #881',
    extractedType: 'account',
    confidenceScore: 78,
    sourceDocument: 'Telco Intercept CDR Batch #44',
    status: 'PENDING'
  },
  {
    id: 'nlp-4',
    textSnippet: 'Dmitri Volkov signed lease agreement for Apex Global Holdings Ltd on August 10th at Brooklyn Navy Yard.',
    extractedName: 'Dmitri Volkov',
    extractedType: 'person',
    confidenceScore: 89,
    sourceDocument: 'Lease Agreement Doc #88491',
    status: 'APPROVED'
  },
  {
    id: 'nlp-5',
    textSnippet: 'A bank transfer of $450,000 was executed from Chase Account #****-9921 to Cayman Islands Offshore Trust.',
    extractedName: '$450,000 Transfer',
    extractedType: 'event',
    confidenceScore: 95,
    sourceDocument: 'SWIFT MT103 Log',
    status: 'APPROVED'
  }
];

export const MOCK_PATTERNS: PatternAnomaly[] = [
  {
    id: 'pat-1',
    caseId: 'case-2291',
    title: 'Circular Offshore Funds Routing',
    type: 'CIRCULAR_FUNDS',
    severity: 'HIGH',
    description: 'Chase Account #****-9921 routed $450,000 to Offshore Trust Cayman #881, which immediately recirculated $420,000 back to Apex Global Holdings via shell invoices.',
    entitiesInvolved: ['ent-7', 'ent-9', 'ent-3', 'ent-2'],
    timestamp: '2026-08-25T02:14:00Z',
    evidenceSnippet: 'Wire MT103 Ref #SW-99120 paired with SWIFT MT103 Ref #SW-99124 within 3 hours.',
    status: 'UNREVIEWED'
  },
  {
    id: 'pat-2',
    caseId: 'case-2291',
    title: 'Pre-Event Burner Phone Call Burst',
    type: 'CALL_SPIKE_PRE_EVENT',
    severity: 'HIGH',
    description: 'Burner phone +1-555-019-4821 exhibited a 600% spike in call frequency to Dmitri Volkov 30 minutes prior to ALPR hit at Pier 42 Depot.',
    entitiesInvolved: ['ent-4', 'ent-8', 'ent-5', 'ent-6'],
    timestamp: '2026-08-24T02:45:00Z',
    evidenceSnippet: '14 calls recorded between 02:15 AM and 02:45 AM, all lasting under 30 seconds.',
    status: 'INVESTIGATING'
  },
  {
    id: 'pat-3',
    caseId: 'case-2291',
    title: 'Co-Location of Key Suspects at Unregistered Facility',
    type: 'CO_LOCATION_CLUSTER',
    severity: 'MEDIUM',
    description: 'Cell tower ping data indicates Viktor Rostov, Elena Rostova, and Marco Rossi were co-located at Pier 42 Terminal for 120 minutes.',
    entitiesInvolved: ['ent-1', 'ent-2', 'ent-11', 'ent-6'],
    timestamp: '2026-08-23T23:00:00Z',
    evidenceSnippet: 'Cell Sector 401-B overlapping pings recorded on 3 distinct IMEI numbers.',
    status: 'UNREVIEWED'
  },
  {
    id: 'pat-4',
    caseId: 'case-4412',
    title: 'Rapid Asset Liquidation & Crypto Conversion',
    type: 'RAPID_ASSET_DISPOSAL',
    severity: 'HIGH',
    description: 'Apex Global Holdings account liquidated $1.2M in short term paper and purchased USDT via OTC desk.',
    entitiesInvolved: ['ent-3', 'ent-7'],
    timestamp: '2026-08-24T14:10:00Z',
    evidenceSnippet: 'Bank statement line item OTC-CRYPTO-DESK-441.',
    status: 'UNREVIEWED'
  }
];

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 'evt-1',
    caseId: 'case-2291',
    entityId: 'ent-1',
    timestamp: '2026-08-24T14:00:00Z',
    title: 'Inter-Agency Intelligence Brief Filed',
    type: 'Intel Report',
    sourceTag: 'INTEL_REPORT',
    locationName: 'NYPD Counterterror Task Force',
    description: 'Dossier updated linking Viktor Rostov to Apex Global Holdings offshore entity structure.',
    linkedEntityIds: ['ent-1', 'ent-3']
  },
  {
    id: 'evt-2',
    caseId: 'case-2291',
    entityId: 'ent-7',
    timestamp: '2026-08-24T23:14:00Z',
    title: 'Wire Transfer Outflow ($450,000)',
    type: 'Financial Wire',
    sourceTag: 'FINANCIAL',
    locationName: 'Wall Street Branch portal',
    description: '$450,000 sent from Chase Account #****-9921 to Cayman Islands Offshore Trust.',
    linkedEntityIds: ['ent-7', 'ent-9', 'ent-2']
  },
  {
    id: 'evt-3',
    caseId: 'case-2291',
    entityId: 'ent-5',
    timestamp: '2026-08-25T03:15:00Z',
    title: 'ALPR Camera Hit at Pier 42 Terminal',
    type: 'Surveillance Hit',
    sourceTag: 'SURVEILLANCE',
    coordinates: [40.7101, -73.9785],
    locationName: 'Pier 42 Marine Terminal',
    description: 'Black SUV (NY-771-X99) recorded entering restricted dock section.',
    linkedEntityIds: ['ent-5', 'ent-6', 'ent-8']
  },
  {
    id: 'evt-4',
    caseId: 'case-2291',
    entityId: 'ent-4',
    timestamp: '2026-08-25T09:30:00Z',
    title: 'Encrypted CDR Call Burst Intercepted',
    type: 'CDR Intercept',
    sourceTag: 'CDR',
    locationName: 'Cell Sector Metro 4',
    description: '14 rapid calls recorded between Burner MSISDN +1-555-019-4821 and Dmitri Volkov.',
    linkedEntityIds: ['ent-4', 'ent-8']
  }
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    timestamp: '2026-08-25T19:10:04Z',
    user: 'Analyst J. Vance (Badge #8804)',
    role: 'Lead Analyst',
    action: 'GRAPH_EXPORT_PDF',
    target: 'Network Graph Case #2291',
    caseId: 'CASE-2026-2291',
    ipAddress: '10.240.18.42'
  },
  {
    id: 'log-102',
    timestamp: '2026-08-25T18:45:12Z',
    user: 'Analyst J. Vance (Badge #8804)',
    role: 'Lead Analyst',
    action: 'NLP_ENTITY_APPROVE',
    target: 'Extracted Entity: Dmitri Volkov',
    caseId: 'CASE-2026-2291',
    ipAddress: '10.240.18.42'
  },
  {
    id: 'log-103',
    timestamp: '2026-08-25T16:20:00Z',
    user: 'Supervisor M. Sterling',
    role: 'Supervisor',
    action: 'CASE_STATUS_CHANGE',
    target: 'Case #2291 → UNDER_INVESTIGATION',
    caseId: 'CASE-2026-2291',
    ipAddress: '10.240.12.09'
  },
  {
    id: 'log-104',
    timestamp: '2026-08-25T14:02:30Z',
    user: 'Investigator S. Chen',
    role: 'Investigator',
    action: 'ENTITY_DOSSIER_VIEW',
    target: 'Viktor Rostov (ent-1)',
    caseId: 'CASE-2026-2291',
    ipAddress: '10.240.19.88'
  }
];
